bind a None
bind b None
bind x None
bind y None
bind back None
bind start None
bind leftshoulder None
bind leftstick None
bind lefttrigger None
bind rightshoulder None
bind rightstick None
bind righttrigger None
bind dpadup None
bind dpaddown None
bind dpadleft None
bind dpadright None
bind dpadupleft None
bind dpadupright None
bind dpaddownright None
bind dpaddownleft None